#redtomato:
#  security:
#    browser:
#      loginPage: /demo-signIn.html
#      loginType: REDIRECT
redtomato:
  security:
    code:
      image:
        length: 2
#        url: /users,/users/*

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test
    username: root
    password: abc221..
  jpa:
    show-sql: true